"""O*NET coverage check of the catalog (ADR-0025): do the roadmaps include what employers ask for?

For each role, the "hot" and "in demand" technologies O*NET 31.0 lists for the role's occupation
(Software Skills.txt) are mapped to catalog skills: through the skills' `onet` names first, then the
name lookup of ADR-0030. Each technology is then covered (in the role's roadmap), in the catalog but not in
the role (a candidate addition), or not in the catalog (a candidate new skill, often a product name).
The report is evidence for review, not an automatic change.
"""

import csv
from collections import Counter
from dataclasses import dataclass, field
from pathlib import Path

from xcrs.catalog.model import Catalog, RoleLevel
from xcrs.catalog.validate import requirements
from xcrs.domain.skill_matching import LexicalIndex

SOFTWARE_SKILLS = "Software Skills.txt"


@dataclass
class Technology:
    name: str
    hot: bool
    in_demand: bool
    skills: tuple[str, ...]  # catalog skills it maps to


@dataclass
class RoleCoverage:
    role: str
    occupation: str
    covered: list[Technology] = field(default_factory=list)
    in_catalog_not_role: list[Technology] = field(default_factory=list)
    not_in_catalog: list[Technology] = field(default_factory=list)

    @property
    def share(self) -> float:
        mapped = len(self.covered) + len(self.in_catalog_not_role)
        total = mapped + len(self.not_in_catalog)
        return len(self.covered) / total if total else 1.0


def load_technologies(onet_dir: Path) -> dict[str, list[tuple[str, bool, bool]]]:
    """Occupation code -> (technology, hot, in demand) for hot or in-demand technologies."""
    out: dict[str, list[tuple[str, bool, bool]]] = {}
    with (onet_dir / SOFTWARE_SKILLS).open(encoding="utf-8") as f:
        for row in csv.DictReader(f, delimiter="\t"):
            hot, demand = row["Hot Technology"] == "Y", row["In Demand"] == "Y"
            if hot or demand:
                out.setdefault(row["O*NET-SOC Code"], []).append((row["Workplace Example"], hot, demand))
    return out


def role_skills(cat: Catalog, role_id: str) -> set[str]:
    role = cat.roles[role_id]
    required = {o for options in requirements(cat, RoleLevel(role_id, role.levels[-1])) for o in options}
    optional = {
        o
        for lv in cat.roadmaps[role_id].levels
        for st in lv.stages
        if st.optional
        for it in st.items
        for o in it.options
    }
    return required | optional


def coverage(cat: Catalog, onet_dir: Path) -> list[RoleCoverage]:
    technologies = load_technologies(onet_dir)
    by_onet_name: dict[str, set[str]] = {}
    for skill in cat.skills.values():
        for name in skill.onet:
            by_onet_name.setdefault(name.lower(), set()).add(skill.id)
    index = LexicalIndex.build((s.id, s.name, s.onet) for s in cat.skills.values())
    result = []
    for role in cat.roles.values():
        uses = role_skills(cat, role.id)
        report = RoleCoverage(role.id, role.onet)
        for name, hot, demand in technologies.get(role.onet, []):
            skills = by_onet_name.get(name.lower()) or index.lookup(name)[0]
            tech = Technology(name, hot, demand, tuple(sorted(skills)))
            if not skills:
                report.not_in_catalog.append(tech)
            elif skills & uses:
                report.covered.append(tech)
            else:
                report.in_catalog_not_role.append(tech)
        result.append(report)
    return result


def markdown(cat: Catalog, reports: list[RoleCoverage]) -> str:
    lines = [
        "# Catalog coverage against O*NET 31.0",
        "",
        "Generated by `uv run xcrs catalog coverage` (ADR-0025). For each role, the technologies O*NET marks as",
        "*hot* or *in demand* for the role's occupation, mapped to catalog skills. Several roles share an",
        "occupation (O*NET is broader than market titles), so they share its list. Evidence for review, not",
        "an automatic change: many unmapped items are products (Microsoft Excel, SAP) rather than skills.",
        "",
        "Includes information from the O*NET 31.0 Database by USDOL/ETA, used under CC BY 4.0, modified by",
        "XCRS; USDOL/ETA has not approved or endorsed it.",
        "",
        "| Role | O*NET | Covered | In catalog, not in role | Not in catalog | Covered share |",
        "|---|---|---|---|---|---|",
    ]
    for r in sorted(reports, key=lambda r: r.share):
        lines.append(
            f"| {cat.roles[r.role].name} | {r.occupation} | {len(r.covered)} | {len(r.in_catalog_not_role)} | "
            f"{len(r.not_in_catalog)} | {r.share:.0%} |"
        )
    lines += ["", "## Candidate additions per role (in demand first)", ""]
    for r in sorted(reports, key=lambda r: cat.roles[r.role].name):
        if not r.in_catalog_not_role:
            continue
        ordered = sorted(r.in_catalog_not_role, key=lambda t: (not t.in_demand, not t.hot, t.name))
        items = ", ".join(
            f"{t.name} → {'/'.join(t.skills)}{' (in demand)' if t.in_demand else ''}" for t in ordered[:12]
        )
        lines.append(f"- **{cat.roles[r.role].name}:** {items}")
    missing = Counter(t.name for r in reports for t in r.not_in_catalog if t.in_demand)
    lines += ["", "## In-demand technologies not in the catalog (by number of roles)", ""]
    lines.append(", ".join(f"{name} ({n})" for name, n in missing.most_common(60)) or "None.")
    return "\n".join(lines) + "\n"
